### ISSUE TITLE
Error on vv lyric database export

### ISSUE THREAD

**Issue by johnhydenc** [verseview/VerseVIEW10_issues#2]
![IMG20240330221937.jpg](https://github.com/verseview/VerseVIEW10_issues/assets/121368244/4fcaa3e1-8df2-490e-9bd9-e19161b92d50)

**Comment by johnhydenc** [comment]
Happens when there is no folder called 'vvexport' in Desktop

**Comment by verseview** [comment]
Fixed issue in build #27. Added code to check if folder exists before trying to write the file. If the file does not exist, then it will create that folder.
